---
- name: Install Redis
  apt:
    name: "redis-server={{ redis_version }}"
    state: present
    update_cache: yes

- name: Create Redis configuration directory
  file:
    path: /etc/redis
    state: directory
    mode: '0755'

- name: Configure Redis
  template:
    src: redis.conf.j2
    dest: /etc/redis/redis.conf
    mode: '0644'
  notify: Restart Redis

- name: Ensure Redis is running and enabled on boot
  service:
    name: redis-server
    state: started
    enabled: yes
